permalink: /:categories/:title
markdown: kramdown
exclude: ['Rakefile', 'CNAME', 'sass/', 'script/', 'README.md']

url: http://jayrambhia.com

name: "Jay Rambhia"
tagline: "Make computers see"
description: "Notes and codes of a paranoid android who wants to make applications to solve real world problems"
about: "I'm <strong>Jay Rambhia</strong>. I'm currently working in the field of Computer Vision. I also like to spend time creating applications."
author:
 name: "Jay Rambhia"
 email: "jayrambhia777@gmail.com"
 github: "jayrambhia"
 twitter: "jayrambhia"
 facebook: "jay.rambhia"
