permalink: /:categories/:title
auto: true
markdown: kramdown
exclude: Rakefile, CNAME, sass/, script/, README.md

#url: http://aniketpant.com

name: "Aniket Pant"
tagline: "Rawrrr!"
description: "Notes and Essays by a developer"
about: "I'm <strong>Aniket</strong>. I love to code, listen to music and I even write free-verses at times. A majority of my work is <em>writing syntax for design</em>."
author:
 name: "Aniket Pant"
 email: "me@aniketpant.com"
 github: "aniketpant"
 twitter: "aniket_pant"
 facebook: "aniket.pant"
