permalink: /:categories/:title
markdown: kramdown
exclude: ['Rakefile', 'CNAME', 'sass/', 'script/', 'README.md']

url: http://jayrambhia.com

name: "Jay Rambhia"
tagline: "Don't Panic!"
description: "Notes and codes of a paranoid android"
about: "I'm <strong>Jay Rambhia</strong>, solving problems one build at a time"
author:
 name: "Jay Rambhia"
 email: "jayrambhia777@gmail.com"
 github: "jayrambhia"
 twitter: "jayrambhia"
 facebook: "jay.rambhia"
